// Maps each skill name in data.js to its brand icon + official color.
// If a skill isn't listed here, it falls back to a generic code icon.
import {
  SiTypescript,
  SiJavascript,
  SiPython,
  SiCplusplus,
  SiC,
  SiHtml5,
  SiCss,
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiSocketdotio,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiRedis,
  SiLinux,
  SiDocker,
  SiNginx,
  SiReact,
  SiRedux,
  SiBootstrap,
  SiGit,
  SiGithub,
  SiGitlab,
  SiPostman,
  SiVercel,
  SiJira,
  SiPhp,
  SiGo,
  SiDart,
  SiRabbitmq,
  SiJsonwebtokens,
  SiSqlite,
  SiPrisma,
  SiKubernetes,
  SiGithubactions,
  SiNextdotjs,
  SiTailwindcss,
  SiVuedotjs,
  SiSemanticuireact,
  SiFramer,
  SiSass,
  SiFigma,
  SiVite,
} from "react-icons/si";
import {
  FaJava,
  FaDatabase,
  FaServer,
  FaSitemap,
  FaAws,
  FaLayerGroup,
  FaMobileAlt,
  FaProjectDiagram,
  FaCube,
  FaDraftingCompass,
  FaPuzzlePiece,
  FaCheckCircle,
  FaVial,
  FaSyncAlt,
  FaCode,
  FaNetworkWired,
  FaMemory,
  FaUsers,
  FaCodeBranch,
} from "react-icons/fa";

export const skillIcons = {
  // Core Languages
  TypeScript: [SiTypescript, "#3178c6"],
  "JavaScript (ES6+)": [SiJavascript, "#f7df1e"],
  Python: [SiPython, "#4b8bbe"],
  PHP: [SiPhp, "#777bb4"],
  Java: [FaJava, "#f89820"],
  "C++": [SiCplusplus, "#659ad2"],
  C: [SiC, "#a8b9cc"],
  Go: [SiGo, "#00add8"],
  Dart: [SiDart, "#0175c2"],
  SQL: [FaDatabase, "#e38c00"],
  HTML5: [SiHtml5, "#e34f26"],
  CSS3: [SiCss, "#663399"],
  // Backend
  "Node.js": [SiNodedotjs, "#8cc84b"],
  "Express.js": [SiExpress, "#eeeeee"],
  NestJS: [SiNestjs, "#e0234e"],
  "RESTful API Design": [FaServer, "#38bdf8"],
  "JWT Authentication": [SiJsonwebtokens, "#d63aff"],
  RabbitMQ: [SiRabbitmq, "#ff6600"],
  "Real-time Systems (Socket.IO)": [SiSocketdotio, "#eeeeee"],
  "System Architecture": [FaSitemap, "#2dd4bf"],
  // Databases
  PostgreSQL: [SiPostgresql, "#699eca"],
  MySQL: [SiMysql, "#5d87a1"],
  MongoDB: [SiMongodb, "#47a248"],
  Redis: [SiRedis, "#dc382d"],
  SQLite: [SiSqlite, "#003b57"],
  "Prisma ORM": [SiPrisma, "#5a67d8"],
  "Database Design & Optimization": [FaDatabase, "#34d399"],
  // DevOps & Cloud
  Linux: [SiLinux, "#fcc624"],
  Docker: [SiDocker, "#2496ed"],
  Kubernetes: [SiKubernetes, "#326ce5"],
  "GitHub Actions": [SiGithubactions, "#2088ff"],
  AWS: [FaAws, "#ff9900"],
  Nginx: [SiNginx, "#009639"],
  // Frontend
  "React.js": [SiReact, "#61dafb"],
  "Next.js": [SiNextdotjs, "#eeeeee"],
  "Tailwind CSS": [SiTailwindcss, "#38bdf8"],
  "Vue.js": [SiVuedotjs, "#42b883"],
  "Semantic UI": [SiSemanticuireact, "#35bdb2"],
  "Framer Motion": [SiFramer, "#e64bff"],
  Sass: [SiSass, "#cc6699"],
  "Redux Toolkit": [SiRedux, "#764abc"],
  "State Management": [FaLayerGroup, "#38bdf8"],
  "Responsive Web Design": [FaMobileAlt, "#2dd4bf"],
  Bootstrap: [SiBootstrap, "#7952b3"],
  // Core CS
  "Data Structures & Algorithms": [FaProjectDiagram, "#f43f5e"],
  "Computer Networks": [FaNetworkWired, "#38bdf8"],
  "Object-Oriented Programming (OOP)": [FaCube, "#fb923c"],
  "Operating Systems": [FaMemory, "#a78bfa"],
  "System Design": [FaDraftingCompass, "#38bdf8"],
  "Design Patterns": [FaPuzzlePiece, "#a78bfa"],
  // Methodologies
  "Clean Code & SOLID": [FaCheckCircle, "#34d399"],
  "Code Review": [FaCodeBranch, "#38bdf8"],
  "Pair Programming": [FaUsers, "#f59e0b"],
  "TDD / BDD": [FaVial, "#f472b6"],
  "Agile / Scrum": [FaSyncAlt, "#38bdf8"],
  // Tools
  Git: [SiGit, "#f05032"],
  GitHub: [SiGithub, "#eeeeee"],
  GitLab: [SiGitlab, "#fc6d26"],
  Postman: [SiPostman, "#ff6c37"],
  Vercel: [SiVercel, "#eeeeee"],
  Vite: [SiVite, "#a259ff"],
  Jira: [SiJira, "#2684ff"],
};

export function SkillIcon({ name, size = 24 }) {
  const entry = skillIcons[name];
  const Cmp = entry ? entry[0] : FaCode;
  const color = entry ? entry[1] : "#8b98ab";
  return <Cmp size={size} color={color} aria-hidden="true" />;
}
